name = "Gungnir"
uuid = "63878dc0-8f17-4645-90ef-67778dd4e687"
authors = ["Frames White <me@oxinabox.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
